const { Client, GatewayIntentBits, SlashCommandBuilder, EmbedBuilder, REST, Routes } = require('discord.js');
const fs = require('fs');
const express = require('express');
const app = express();
const client = new Client({ intents: [GatewayIntentBits.Guilds] });

const KEYS_FILE = './keys.json';
const OWNER_USERNAME = 'Unknown007016';

// HTTP server for UptimeRobot
const PORT = process.env.PORT || 3000;

app.get('/', (req, res) => {
    res.send('Bot is running 24/7!');
});

app.get('/health', (req, res) => {
    res.status(200).json({ status: 'ok', timestamp: new Date().toISOString() });
});

app.listen(PORT, '0.0.0.0', () => {
    console.log(`✅ HTTP server running on port ${PORT}`);
});

function generateKey() {
    const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
    let key = 'Shadow-';
    for (let i = 0; i < 6; i++) key += chars[Math.floor(Math.random() * chars.length)];
    return key;
}

function loadKeys() {
    if (!fs.existsSync(KEYS_FILE)) fs.writeFileSync(KEYS_FILE, '[]');
    try {
        return JSON.parse(fs.readFileSync(KEYS_FILE, 'utf8'));
    } catch (e) {
        return [];
    }
}

function saveKeys(keys) {
    fs.writeFileSync(KEYS_FILE, JSON.stringify(keys, null, 2));
}

// FIXED: Changed from 'ready' to 'clientReady' or use once()
client.once('ready', () => {
    console.log(`✅ Bot ready: ${client.user.tag}`);
    console.log(`✅ Bot is online and will run 24/7!`);
    client.user.setActivity('/setup | 24/7', { type: 'Playing' });
});

client.on('interactionCreate', async (interaction) => {
    if (!interaction.isChatInputCommand()) return;

    const isOwner = interaction.user.username === OWNER_USERNAME;

    if (interaction.commandName === 'setup') {
        if (!isOwner) {
            // FIXED: Changed ephemeral to flags: 64
            return interaction.reply({ content: '❌ Owner only!', flags: 64 });
        }

        const key = generateKey();
        const keys = loadKeys();
        keys.push({
            key: key,
            generatedBy: interaction.user.id,
            generatedAt: new Date().toISOString(),
            used: false,
            usedBy: null,
            hwid: null
        });
        saveKeys(keys);

        const embed = new EmbedBuilder()
            .setTitle('🔑 Shadow Hub Key Generated')
            .setDescription(`**Key:** \`${key}\`\n**Game:** Flick/Onetap\n**Generated by:** <@${interaction.user.id}>`)
            .setColor(0x7848FF)
            .setTimestamp();

        await interaction.reply({ embeds: [embed] });

        // FIXED: Added error handling for log channel
        const logChannel = interaction.guild.channels.cache.find(c => c.name === 'key-logs');
        if (logChannel) {
            try {
                await logChannel.send({ embeds: [embed] });
            } catch (error) {
                console.error('Failed to send to log channel:', error);
            }
        }
    }

    if (interaction.commandName === 'keys') {
        if (!isOwner) {
            return interaction.reply({ content: '❌ Owner only!', flags: 64 });
        }

        const keys = loadKeys().filter(k => !k.used);
        const embed = new EmbedBuilder()
            .setTitle('📋 Active Keys')
            .setDescription(keys.length > 0 ? keys.map(k => `\`${k.key}\``).join('\n') : 'No active keys')
            .setColor(0x7848FF);

        await interaction.reply({ embeds: [embed], flags: 64 });
    }

    if (interaction.commandName === 'revoke') {
        if (!isOwner) {
            return interaction.reply({ content: '❌ Owner only!', flags: 64 });
        }

        const key = interaction.options.getString('key');
        const keys = loadKeys();
        const idx = keys.findIndex(k => k.key === key);

        if (idx === -1) {
            return interaction.reply({ content: '❌ Key not found!', flags: 64 });
        }

        keys.splice(idx, 1);
        saveKeys(keys);

        await interaction.reply({ content: `✅ Key \`${key}\` revoked!`, flags: 64 });
    }
});

const commands = [
    new SlashCommandBuilder().setName('setup').setDescription('Generate new Shadow Hub key (Owner only)'),
    new SlashCommandBuilder().setName('keys').setDescription('List all active keys (Owner only)'),
    new SlashCommandBuilder().setName('revoke').setDescription('Revoke a key (Owner only)')
        .addStringOption(opt => opt.setName('key').setDescription('Key to revoke').setRequired(true))
];

const rest = new REST({ version: '10' }).setToken(process.env.BOT_TOKEN);

(async () => {
    try {
        await rest.put(Routes.applicationCommands(process.env.CLIENT_ID), { body: commands });
        console.log('✅ Commands registered!');
    } catch (error) {
        console.error('❌ Error registering commands:', error);
    }
})();

client.login(process.env.BOT_TOKEN);
