const { Client, GatewayIntentBits, SlashCommandBuilder, EmbedBuilder, REST, Routes } = require('discord.js');
const fs = require('fs');
const express = require('express');

// Initialize Express for Render survival
const app = express();
const PORT = process.env.PORT || 3000;

app.get('/', (req, res) => res.send('Bot is online!'));
app.get('/health', (req, res) => res.status(200).send('OK'));

app.listen(PORT, '0.0.0.0', () => {
    console.log(`✅ Web server active on port ${PORT}`);
});

// Bot Configuration
const client = new Client({ intents: [GatewayIntentBits.Guilds] });
const KEYS_FILE = './keys.json';
const OWNER_USERNAME = 'unknown007016'; // Lowercase for safer comparison

// Helper Functions
function loadKeys() {
    try {
        if (!fs.existsSync(KEYS_FILE)) return [];
        const data = fs.readFileSync(KEYS_FILE, 'utf8');
        return JSON.parse(data);
    } catch (e) {
        console.error("Error loading keys:", e);
        return [];
    }
}

function saveKeys(keys) {
    fs.writeFileSync(KEYS_FILE, JSON.stringify(keys, null, 2));
}

function generateKey() {
    const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
    let key = 'Shadow-';
    for (let i = 0; i < 6; i++) {
        key += chars[Math.floor(Math.random() * chars.length)];
    }
    return key;
}

// Commands Registration
const commands = [
    new SlashCommandBuilder()
        .setName('setup')
        .setDescription('Generate new Shadow Hub key (Owner only)'),
    new SlashCommandBuilder()
        .setName('keys')
        .setDescription('List all active keys (Owner only)'),
    new SlashCommandBuilder()
        .setName('revoke')
        .setDescription('Revoke a key (Owner only)')
        .addStringOption(opt => opt.setName('key').setDescription('Key to revoke').setRequired(true))
].map(command => command.toJSON());

// Lifecycle Events
client.once('ready', async () => {
    console.log(`✅ Logged in as ${client.user.tag}`);
    
    const rest = new REST({ version: '10' }).setToken(process.env.BOT_TOKEN);
    try {
        await rest.put(
            Routes.applicationCommands(process.env.CLIENT_ID),
            { body: commands }
        );
        console.log('✅ Slash commands registered globally');
    } catch (error) {
        console.error('❌ Failed to register commands:', error);
    }
});

client.on('interactionCreate', async (interaction) => {
    if (!interaction.isChatInputCommand()) return;

    // Check username (case-insensitive)
    const isOwner = interaction.user.username.toLowerCase() === OWNER_USERNAME.toLowerCase();

    if (!isOwner) {
        return interaction.reply({ 
            content: '❌ You do not have permission to use this command.', 
            ephemeral: true 
        });
    }

    if (interaction.commandName === 'setup') {
        const key = generateKey();
        const keys = loadKeys();
        
        const newKey = {
            key: key,
            generatedBy: interaction.user.tag,
            at: new Date().toISOString(),
            used: false
        };
        
        keys.push(newKey);
        saveKeys(keys);

        const embed = new EmbedBuilder()
            .setTitle('🔑 Key Generated')
            .addFields(
                { name: 'Key', value: `\`${key}\`` },
                { name: 'Generated By', value: `${interaction.user.tag}` }
            )
            .setColor(0x7848FF)
            .setTimestamp();

        await interaction.reply({ embeds: [embed] });
    }

    if (interaction.commandName === 'keys') {
        const keys = loadKeys();
        const activeKeys = keys.filter(k => !k.used);
        
        const embed = new EmbedBuilder()
            .setTitle('📋 Active Keys')
            .setDescription(activeKeys.length > 0 ? activeKeys.map(k => `\`${k.key}\``).join('\n') : 'No active keys')
            .setColor(0x00FF00);

        await interaction.reply({ embeds: [embed], ephemeral: true });
    }

    if (interaction.commandName === 'revoke') {
        const targetKey = interaction.options.getString('key');
        let keys = loadKeys();
        const exists = keys.some(k => k.key === targetKey);

        if (!exists) {
            return interaction.reply({ content: '❌ Key not found.', ephemeral: true });
        }

        keys = keys.filter(k => k.key !== targetKey);
        saveKeys(keys);

        await interaction.reply({ content: `✅ Key \`${targetKey}\` has been deleted.`, ephemeral: true });
    }
});

client.login(process.env.BOT_TOKEN);
